---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml


  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      ansible.builtin.wait_for_connection:
        timeout: 900

    - name: "install python for Ansible."
      apt:
           name: 
            - python3
            - nodejs
           state: latest
           update_cache: yes
    - name : link python3 as python
      shell : alias python='python3'
 
  # Get the environment variables from CircleCI and add to the EC2 instance

  roles:
    - configure-server
    - configure-prometheus-node-exporter