---
- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false

  roles:
    - configure-server
