    - name: run the app container
      docker_container:
        name: capstone
        state: started
        image: "yaqot/microserviceapp"
        pull: true
        ports:
          - "8080:8080"
