version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
